# Use localhost for testing
group_localhost:
  hosts:
    localhost:
      ansible_connection: "local"
      ansible_python_interpreter: "/usr/bin/python3"
  vars:
    group: "csc"
    appl_dir: "{{ ansible_env.HOME }}/scratch/appl/soft/math"
    modulefiles_dir: "{{ ansible_env.HOME}}/scratch/appl/modulefiles"
group_puhti:
  hosts:
    puhti-install:
      ansible_connection: "ssh"
      ansible_python_interpreter: "/usr/bin/python3.9"
  vars:
    group: "p_installation"
    appl_dir: "/appl/soft/math"
    modulefiles_dir: "/appl/modulefiles"
