- name: "Install matlab environment"
  hosts:
    - "group_localhost"
    - "group_puhti"
  become: false
  vars:
    matlab_version: "r2023b"

  tasks:
    - name: "Create a matlab application directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "matlab"
        - "matlab/interactive"
        - "matlab/interactive/{{ matlab_version }}"
        - "matlab/interactive/{{ matlab_version }}/bin"

    - name: "Copy the wrapper scripts"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ matlab_version }}/bin/{{ item }}"
        dest: "{{ appl_dir }}/matlab/interactive/{{ matlab_version }}/bin/{{ item }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - "matlab"
        - "mcc"
        - "mbuild"
        - "mex"

    - name: "Create a matlab modulefiles directory"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/matlab"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Copy the modulefile"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ matlab_version }}/matlab.lua"
        dest: "{{ modulefiles_dir }}/matlab/{{ matlab_version }}.lua"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: "Copy the installation"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ matlab_version }}/matlab.sif"
        dest: "{{ appl_dir }}/matlab/interactive/{{ matlab_version }}/matlab.sif"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
