- name: "Install mps environment"
  hosts:
    - "group_localhost"
    - "group_puhti"
  become: false
  vars:
    version: "r2023b"

  tasks:
    - name: "Create a mps application directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "matlab"
        - "matlab/mps"
        - "matlab/mps/{{ version }}"
        - "matlab/mps/{{ version }}/bin"

    - name: "Copy the wrapper scripts"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ version }}/bin/{{ item }}"
        dest: "{{ appl_dir }}/matlab/mps/{{ version }}/bin/{{ item }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - "apptainer_exec"
        - "matlab"
        - "mex"

    - name: "Copy the wrapper script templates"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/{{ version }}/bin/{{ item }}.j2"
        dest: "{{ appl_dir }}/matlab/mps/{{ version }}/bin/{{ item }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - "worker"

    - name: "Create directories"
      ansible.builtin.file:
        path: "{{ appl_dir }}/matlab/mps/{{ version }}/bin/{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "util"
        - "glnxa64"

    - name: "Copy certain binaries from build"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ version }}/build/bin/{{ item }}"
        dest: "{{ appl_dir }}/matlab/mps/{{ version }}/bin/{{ item }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - "mw_mpiexec"
        - "mw_smpd"
        - "util/arch.sh"
        - "glnxa64/mpiexec"
        - "glnxa64/mpiexec.hydra"
        - "glnxa64/hydra_pmi_proxy"
        - "glnxa64/mpiexec2"
        - "glnxa64/smpd"
        - "glnxa64/libssl-mw.so.3"
        - "glnxa64/libcrypto-mw.so.3"

    - name: "Create a mps modulefiles directory"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/mps"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Copy the modulefile"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ version }}/matlab.lua"
        dest: "{{ modulefiles_dir }}/mps/{{ version }}.lua"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: "Copy the installation"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ version}}/matlab.sif"
        dest: "{{ appl_dir }}/matlab/mps/{{ version }}/matlab.sif"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      tags:
        - "large"

    - name: "Link matlab-proxy to matlab for ood-matlab-html"
      ansible.builtin.file:
        src: "matlab"
        dest: "{{ modulefiles_dir }}/matlab-parallel-server"
        state: "link"
        group: "{{ group }}"
