- name: "Install matlab environment"
  hosts:
    - "group_localhost"
    - "group_puhti"
  become: false

  tasks:
    - name: "Create a matlab application directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "matlab"
        - "matlab/mps"
        - "matlab/mps/{{ version }}"
        - "matlab/mps/{{ version }}/bin"

    - name: "Copy the wrapper scripts"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ version }}/bin/{{ item }}"
        dest: "{{ appl_dir }}/matlab/mps/{{ version }}/bin/{{ item }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - "apptainer_exec"
        - "matlab"
        - "mex"
        - "matlab-proxy-app"

    - name: "Copy the wrapper script templates"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/{{ version }}/bin/{{ item }}.j2"
        dest: "{{ appl_dir }}/matlab/mps/{{ version }}/bin/{{ item }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - "worker"

    - name: "Create a matlab modulefiles directory"
      ansible.builtin.file:
        path: "{{ modulefiles_dir }}/matlab"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"

    - name: "Copy the modulefile"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/{{ version }}/matlab.lua"
        dest: "{{ modulefiles_dir }}/matlab/{{ version }}.lua"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: "Link matlab-proxy to matlab for ood-matlab-html"
      ansible.builtin.file:
        src: "mps"
        dest: "{{ modulefiles_dir }}/matlab-proxy"
        state: "link"
        group: "{{ group }}"
