- name: "Install Mathworks ServiceHost"
  hosts:
    - "puhti"
    - "mahti"
  become: false

  tasks:
    - name: "Include variables"
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/version/{{ version }}.yaml"

    - name: "Create Mathworks ServiceHost directory"
      ansible.builtin.file:
        path: "{{ appl_dir }}/{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "mathworksservicehost"
        - "mathworksservicehost/{{ version }}"

    - name: "Download the mathworks servicehost"
      ansible.builtin.get_url:
        url: "https://ssd.mathworks.com/supportfiles/downloads/MathWorksServiceHost/v{{ version }}/release/glnxa64/managed_mathworksservicehost_{{ version }}_package_glnxa64.zip"
        dest: "{{ appl_dir }}/mathworksservicehost/{{ version }}.zip"
        checksum: "{{ checksum }}"
        mode: "ug=rw,o=r"
        group: "{{ group }}"

    - name: "Unzip the servicehost"
      ansible.builtin.unarchive:
        src: "{{ appl_dir }}/mathworksservicehost/{{ version }}.zip"
        dest: "{{ appl_dir }}/mathworksservicehost/{{ version }}"
        remote_src: true
        group: "{{ group }}"
        creates: "{{ appl_dir }}/mathworksservicehost/{{ version }}/bin"

    - name: "Write LatestInstall.info"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/LatestInstall.info.j2"
        dest: "{{ appl_dir }}/mathworksservicehost/LatestInstall.info"
        group: "{{ group }}"
