- name: "Install matlab environment"
  hosts:
    - "lumi"
  become: false

  tasks:
    - name: "Directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "{{ appl_dir }}/matlab"
        - "{{ appl_dir }}/matlab/{{ version }}"
        - "{{ appl_dir }}/matlab/{{ version }}/bin"
        - "{{ modulefiles_dir }}/matlab"

    - name: "Executable scripts"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - src: "{{ playbook_dir }}/version/{{ version }}/bin/matlab"
          dest: "{{ appl_dir }}/matlab/{{ version }}/bin/matlab"
        - src: "{{ playbook_dir }}/version/{{ version }}/bin/matlab-proxy-app"
          dest: "{{ appl_dir }}/matlab/{{ version }}/bin/matlab-proxy-app"

    - name: "Executable script templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "ug=rwx,o=rx"
        group: "{{ group }}"
      loop:
        - src: "{{ playbook_dir }}/version/{{ version }}/bin/matlab-singularity-exec.j2"
          dest: "{{ appl_dir }}/matlab/{{ version }}/bin/matlab-singularity-exec"

    - name: "Regular files"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "ug=rw,o=r"
        group: "{{ group }}"
      loop:
        - src: "{{ playbook_dir }}/version/{{ version }}/matlab.lua"
          dest: "{{ modulefiles_dir }}/matlab/{{ version }}.lua"

    - name: "Container file dummy. Real container should be scp'ed to its place."
      ansible.builtin.file:
        path: "{{ appl_dir }}/matlab/{{ version }}/matlab.sif"
        state: "touch"
        modification_time: "preserve"
        access_time: "preserve"
        mode: "ug=rwx,o=rx"

- name: "Synchronize across LUMI Lustres"
  hosts:
    - "lumi"
  become: false

  tasks:
    - name: "Create a matlab application directory"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        mode: "ug=rwx,o=rx,g+s"
        group: "{{ group }}"
      loop:
        - "/pfs/lustrep1/{{ appl_dir }}/matlab"
        - "/pfs/lustrep3/{{ appl_dir }}/matlab"
        - "/pfs/lustrep4/{{ appl_dir }}/matlab"

    - name: "Synchronize installation"
      ansible.builtin.command: |
        rsync --archive --delete "{{ item.src }}" "{{ item.dest }}"
      loop:
        - src: "/pfs/lustrep2/{{ appl_dir }}/matlab/{{ version }}"
          dest: "/pfs/lustrep1/{{ appl_dir }}/matlab"
        - src: "/pfs/lustrep2/{{ appl_dir }}/matlab/{{ version }}"
          dest: "/pfs/lustrep3/{{ appl_dir }}/matlab"
        - src: "/pfs/lustrep2/{{ appl_dir }}/matlab/{{ version }}"
          dest: "/pfs/lustrep4/{{ appl_dir }}/matlab"

    - name: "Synchronize modulefiles"
      ansible.builtin.command: |
        rsync --archive --delete "{{ item.src }}" "{{ item.dest }}"
      loop:
        - src: "/pfs/lustrep2/{{ modulefiles_dir }}/matlab"
          dest: "/pfs/lustrep1/{{ modulefiles_dir }}"
        - src: "/pfs/lustrep2/{{ modulefiles_dir }}/matlab"
          dest: "/pfs/lustrep3/{{ modulefiles_dir }}"
        - src: "/pfs/lustrep2/{{ modulefiles_dir }}/matlab"
          dest: "/pfs/lustrep4/{{ modulefiles_dir }}"
